// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Arc struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Arc) Reset()         { *m = Arc{} }
func (m *Arc) String() string { return proto.CompactTextString(m) }
func (*Arc) ProtoMessage()    {}
func (*Arc) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_a4feaa465ca2e152, []int{0}
}
func (m *Arc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arc.Unmarshal(m, b)
}
func (m *Arc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arc.Marshal(b, m, deterministic)
}
func (dst *Arc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arc.Merge(dst, src)
}
func (m *Arc) XXX_Size() int {
	return xxx_messageInfo_Arc.Size(m)
}
func (m *Arc) XXX_DiscardUnknown() {
	xxx_messageInfo_Arc.DiscardUnknown(m)
}

var xxx_messageInfo_Arc proto.InternalMessageInfo

func (m *Arc) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Arc) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Arc)(nil), "protos.Arc")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_a4feaa465ca2e152) }

var fileDescriptor_message_a4feaa465ca2e152 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xba,
	0x5c, 0xcc, 0x8e, 0x45, 0xc9, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x27, 0x08, 0xcc, 0x4e, 0x82, 0x68, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x10, 0x8d,
	0xf0, 0x0b, 0x4e, 0x00, 0x00, 0x00,
}
